apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


patchesStrategicMerge:
- application-depl.yml
- credentials.yml

namespace: <NAME_OF_DEV_NAMESPACE>
images:
- name: <APPLICATION_NAME>-image
  newName: <ECR_REPOSITORY_URL>
