apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APPLICATION_NAME>-depl
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: <APPLICATION_NAME>
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - prod
      containers:
        - name: <APPLICATION_NAME>
          envFrom:
            - secretRef:
                name: <APPLICATION_NAME>-secret