apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: <APPLICATION_NAME>-secret
spec:
  backendType: secretsManager
  region: ap-northeast-2
  dataFrom:
    - <AWS SECRETS MANAGER NAME FOR PROD>
