apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: sync
  namespace: argo-cd
spec:
  backendType: secretsManager
  region: ap-northeast-2
  dataFrom:
    - cd/github-app
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      type: git
      url: https://github.com/<USER_NAME>/<REPOSITORY_NAME>
