apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <APPLICATION_NAME>-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: "open-dev.vreview.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <APPLICATION_NAME>-srv
            port: 
              number: 3000
