apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APPLICATION_NAME>-depl
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: <APPLICATION_NAME>
  template:
    metadata:
      labels:
        app: <APPLICATION_NAME>
    spec:
      containers:
        - name: <APPLICATION_NAME>
          image: <APPLICATION_NAME>-image
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: <APPLICATION_NAME>-secret
